services:
  snapdrop:
    image: linuxserver/snapdrop:version-b8b78cc2
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - "3030:80"
    restart: on-failure 
  apache:
    image: httpd:2.4-alpine
    container_name: apache
    ports:
      - 8081:80
    volumes:
      - ./public:/usr/local/apache2/htdocs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
  code:
    image: lscr.io/linuxserver/code-server:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      PASSWORD: 2SMAzornotza
    volumes:
      - ./:/config/workspace
      - code_config:/config
    ports:
      - "8443:8443"


volumes:
  code_config: